# Generated by Django 3.2.6 on 2022-09-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cretead_at',
            new_name='created_at',
        ),
    ]
